export const shapeNamesHu: Record<string, string> = {
  heart: "szív", star: "csillag", circle: "kör", smiley: "mosoly", triangle: "háromszög", 
  butterfly: "pillangó", fish: "hal", wolf: "farkas", deer: "szarvas", squirrel: "mókus",
  hedgehog: "sün", bee: "méh", ant: "hangya", spider: "pók", seahorse: "csikóhal",
  jellyfish: "medúza", starfish: "tengeri csillag", horse: "ló", cat: "macska", dog: "kutya",
  bird: "madár", rabbit: "nyúl", owl: "bagoly", swan: "hattyú", crow: "varjú",
  penguin: "pingvin", dolphin: "delfin", shark: "cápa", whale: "bálna", snail: "csiga",
  frog: "béka", dragon: "sárkány", unicorn: "unikornis", phoenix: "főnix", peacock: "páva",
  crab: "rák", octopus: "polip", elephant: "elefánt", giraffe: "zsiráf", lion: "oroszlán",
  tiger: "tigris", bear: "medve", snake: "kígyó", turtle: "teknős", parrot: "papagáj",
  tree: "fa", flower: "virág", sun: "nap", moon: "hold", mountain: "hegy",
  wave: "hullám", lightning: "villám", snowflake: "hópehely", volcano: "vulkán",
  waterfall: "vízesés", rainbow: "szivárvány", tornado: "tornádó", island: "sziget",
  desert: "sivatag", forest: "erdő", canyon: "kanyon", glacier: "gleccser",
  aurora: "sarki fény", leaf: "levél", mushroom: "gomba", cloud: "felhő", droplet: "csepp",
  crown: "korona", castle: "kastély", bridge: "híd", parliament: "parlament",
  basilica: "bazilika", "chain-bridge": "lánchíd", opera: "opera", cathedral: "katedrális",
  windmill: "szélmalom", lighthouse: "világítótorony", fountain: "szökőkút", pagoda: "pagoda",
  temple: "templom", pyramid: "piramis", colosseum: "kolosszeum", "eiffel-tower": "eiffel torony",
  statue: "szobor", gate: "kapu", arrow: "nyíl", cross: "kereszt", infinity: "végtelen",
  peace: "béke", "yin-yang": "jin-jang", shield: "pajzs", sword: "kard", ring: "gyűrű",
  crystal: "kristály", gem: "drágakő", star8: "nyolcágú csillag", pentagon: "ötszög",
  octagon: "nyolcszög", "queen-crown": "királynői korona", diamond: "gyémánt", clover: "lóhere",
  anchor: "horgony", key: "kulcs", lock: "lakat", gear: "fogaskerék", compass: "iránytű",
  telescope: "távcső", bicycle: "bicikli", runner: "futó", swimmer: "úszó",
  skateboard: "gördeszka", surfboard: "szörfdeszka", kayak: "kajak", canoe: "kenu",
  "golf-club": "golfütő", "hockey-stick": "hokiütő", volleyball: "röplabda",
  bowling: "bowling", "archery-bow": "íj", parachute: "ejtőernyő", dumbbell: "súlyzó",
  target: "célpont", trophy: "kupa", balloon: "lufi", cake: "torta", "ice-cream": "fagyi",
  donut: "fánk", coffee: "kávé", hotdog: "hotdog", hamburger: "hamburger",
  cocktail: "koktél", pretzel: "perec", sunglasses: "napszemüveg", hat: "kalap",
  mask: "maszk", robot: "robot", rocket: "rakéta", ufo: "ufó", ghost: "szellem",
  skeleton: "csontváz", alien: "űrlény", wink: "kacsint", square: "négyzet",
  hexagon: "hatszög", spiral: "spirál", zigzag: "cikkcakk", ribbon: "szalag",
  loop: "hurok", wavy: "hullámos", chevron: "ék", crosshair: "célkereszt", grid: "rács"
};
